name: Make release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build files
      run: |
        go version
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o action-release.exe
        zip action-release_${{ github.event.release.name }}_Windows-64bit.zip action-release.exe
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Prepare source tarball
      run: |
        git clone -b ${{ github.event.release.name }} --depth 1 https://github.com/schollz/action-release action-release-${{ github.event.release.name }}
        cd action-release-${{ github.event.release.name }} && go mod tidy && go mod vendor
        cd .. && tar -czvf action-release_${{ github.event.release.name }}_src.tar.gz action-release-${{ github.event.release.name }}
    - name: Build files
      run: |
        go version
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o action-release.exe
        zip action-release_${{ github.event.release.name }}_Windows-64bit.zip action-release.exe
        GOOS=windows GOARCH=386 go build -ldflags="-s -w" -o action-release.exe
        zip action-release_${{ github.event.release.name }}_Windows-32bit.zip action-release.exe
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o action-release
        upx --brute action-release
        tar -czvf action-release_${{ github.event.release.name }}_Linux-64bit.tar.gz action-release
        GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o action-release
        tar -czvf action-release_${{ github.event.release.name }}_Linux-32bit.tar.gz action-release
        GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o action-release
        upx --brute action-release
        tar -czvf action-release_${{ github.event.release.name }}_Linux-ARM.tar.gz action-release
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o action-release
        upx --brute action-release
        tar -czvf action-release_${{ github.event.release.name }}_Linux-ARM64.tar.gz action-release
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o action-release
        tar -czvf action-release_${{ github.event.release.name }}_macOS-64bit.tar.gz action-release
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o action-release
        tar -czvf action-release_${{ github.event.release.name }}_macOS-ARM64.tar.gz action-release
    - name: Create checksums.txt
      run: |
        touch action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_src.tar.gz >> action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_Windows-64bit.zip >> action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_Windows-32bit.zip >> action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_Linux-64bit.tar.gz >> action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_Linux-32bit.tar.gz >> action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_Linux-ARM.tar.gz >> action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_Linux-ARM64.tar.gz >> action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_macOS-64bit.tar.gz >> action-release_${{ github.event.release.name }}_checksums.txt
        sha256sum action-release_${{ github.event.release.name }}_macOS-ARM64.tar.gz >> action-release_${{ github.event.release.name }}_checksums.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          action-release_${{ github.event.release.name }}_checksums.txt
          action-release_${{ github.event.release.name }}_src.tar.gz
          action-release_${{ github.event.release.name }}_Windows-64bit.zip
          action-release_${{ github.event.release.name }}_Windows-32bit.zip
          action-release_${{ github.event.release.name }}_Linux-64bit.tar.gz
          action-release_${{ github.event.release.name }}_Linux-32bit.tar.gz
          action-release_${{ github.event.release.name }}_Linux-ARM.tar.gz
          action-release_${{ github.event.release.name }}_Linux-ARM64.tar.gz
          action-release_${{ github.event.release.name }}_macOS-64bit.tar.gz
          action-release_${{ github.event.release.name }}_macOS-ARM64.tar.gz 

