name: Make release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install tar zip
    - name: Build files
      run: |
        go build -o app
        zip app{{ github.event.release.name }}.zip app
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app{{ github.event.release.name }}.zip

